services:
  game-web:
    build:
      context: ./game-web
      dockerfile: ./Dockerfile
    image: game-web
    ports:
      - "3000:3000"
  game-api:
    build:
      context: ./game-api
      dockerfile: ./Dockerfile
    image: game-api
    ports:
      - "3001:3001"
